# Generated by Django 3.0.5 on 2020-04-29 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboard',
            name='zipcode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
