# Generated by Django 3.0.5 on 2020-04-29 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0002_auto_20200429_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboard',
            name='name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$')]),
        ),
    ]
