# Generated by Django 3.0.5 on 2020-04-29 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0006_auto_20200429_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='lockerid',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='occupancy',
            name='lockerid',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='onboard',
            name='country',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', message='Numbers not allowed')]),
        ),
        migrations.AlterField(
            model_name='onboard',
            name='lockerid',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='onboard',
            name='name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', message='Numbers not allowed')]),
        ),
        migrations.AlterField(
            model_name='onboard',
            name='zipcode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='Letters are not allowed'), django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='lockerid',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='throughput',
            name='lockerid',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
