# Generated by Django 3.0.5 on 2020-04-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0008_auto_20200429_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='lockerid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='occupancy',
            name='lockerid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='onboard',
            name='lockerid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='lockerid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='throughput',
            name='lockerid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
