# Generated by Django 3.0.5 on 2020-04-29 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0010_auto_20200429_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='non_del_days',
            field=models.CharField(default='0000000', max_length=7, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='Letters not permissible'), django.core.validators.MinLengthValidator(7)], verbose_name='Non delivery days'),
        ),
    ]
