# Generated by Django 3.0.5 on 2020-04-29 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0012_auto_20200429_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='lockerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lockers.Onboard'),
        ),
        migrations.AlterField(
            model_name='occupancy',
            name='lockerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lockers.Onboard'),
        ),
        migrations.AlterField(
            model_name='throughput',
            name='lockerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lockers.Onboard'),
        ),
    ]
