# Generated by Django 3.0.5 on 2020-04-29 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0013_auto_20200429_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='id',
            field=models.AutoField(auto_created=True, default=101, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='lockerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lockers.Onboard'),
        ),
    ]
